# coding: utf-8

# flake8: noqa

"""
    Quant Trading Network API

    This API will use JSON.         JSON looks like this:                {         \"key\": \"value\",         \"anotherKey\": \"anotherValue\"       }  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@quant-trading.network
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from quant_trading.api.bitcoin_futures_manager_api import BitcoinFuturesManagerApi
from quant_trading.api.bitcoin_futures_market_maker_api import BitcoinFuturesMarketMakerApi
from quant_trading.api.bitcoin_futures_swinger_api import BitcoinFuturesSwingerApi
# import ApiClient
from quant_trading.api_client import ApiClient
from quant_trading.configuration import Configuration
# import models into sdk package
from quant_trading.models.algo_params_response import AlgoParamsResponse
from quant_trading.models.avg_open_position_hours import AvgOpenPositionHours
from quant_trading.models.closed_position_hours import ClosedPositionHours
from quant_trading.models.current_position_pct import CurrentPositionPct
from quant_trading.models.current_unrealised_pct import CurrentUnrealisedPct
from quant_trading.models.error import Error
from quant_trading.models.exec_algo_response import ExecAlgoResponse
from quant_trading.models.exec_position_manager_algo_request import ExecPositionManagerAlgoRequest
from quant_trading.models.exec_position_swinger_algo_request import ExecPositionSwingerAlgoRequest
from quant_trading.models.last_open_stake_hours import LastOpenStakeHours
from quant_trading.models.open_position_hours import OpenPositionHours
from quant_trading.models.position_state import PositionState
from quant_trading.models.stake_state import StakeState
from quant_trading.models.x_rate_limit_limit import XRateLimitLimit
from quant_trading.models.x_rate_limit_remaining import XRateLimitRemaining
from quant_trading.models.x_rate_limit_reset import XRateLimitReset
